### PR TITLE
barebox: update to v2022.02.0-phy

### PR DESCRIPTION
**Pull request by fhunleth**
I needed to update barebox to get support for [ubootvarfs](https://www.barebox.org/doc/latest/filesystems/ubootvarfs.html) for Nerves. This PR aims to do the minimal updates for this. This works for Nerves. I did not try it with GRiSP images, but I really think that it should. Note that I didn't update the committed Barebox binary.

### CODE REVIEW

**Comment by fhunleth** [comment]
It looks like there's a tag that can be used now instead of the `v2022.02.0-phy` branch. See https://git.phytec.de/barebox/tag/?h=v2022.02.0-phy1.

**Comment by sylane** [comment]
I am trying to test this PR, and beside having other issue, I was wondering which of the configuration changes were really needed and which are coming from barebox new version.

There is a lot of configuration key added and removed, I can see the two related to boot, but any more information on the other changes would be nice:

Removed:
CONFIG_DEFCONFIG_LIST
CONFIG_FILE_LIST
CONFIG_BAREBOX_MAX_PBLX_SIZE
CONFIG_COMPILE_MEMORY
CONFIG_CMD_OF_CAMERA_SELECTION
CONFIG_OF_NET
CONFIG_NAND_ECC_SOFT
CONFIG_NAND_ECC_HW
CONFIG_NAND_ECC_HW_NONE
CONFIG_NAND_INFO
CONFIG_NAND_READ_OOB
CONFIG_NAND_BBT
CONFIG_NAND_IMX_BBM
CONFIG_MTD_NAND_IDS
CONFIG_MTD_UBI_WL_THRESHOLD
CONFIG_CRC16

Added:
CONFIG_FASTBOOT_BASE
CONFIG_HAVE_MOD_ARCH_SPECIFIC
CONFIG_HAS_ARCH_SJLJ
CONFIG_ARM_PSCI_OF
CONFIG_HAS_SCHED
CONFIG_EXTERNAL_DTS_FRAGMENTS
CONFIG_HAVE_ARCH_KASAN
CONFIG_CC_HAS_KASAN_GENERIC
CONFIG_CMD_SETENV
CONFIG_SPI_MEM
CONFIG_USB_IMX_CHIPIDEA_USBMISC
CONFIG_USB_OTGDEV
CONFIG_MCI_SDHCI
CONFIG_CLOCKSOURCE_ARM_ARCHITECTED_TIMER
CONFIG_MFD_SYSCON
CONFIG_DEV_MEM
CONFIG_UBOOTVAR                          <---
CONFIG_VIRTIO_MENU
CONFIG_FS_UBOOTVARFS                     <---
CONFIG_ARCH_HAS_STACK_DUMP
CONFIG_ARCH_HAS_DATA_ABORT_MASK

**Comment by fhunleth** [comment]
It has been a really long time and I've totally forgotten where the other changes came from. `CONFIG_UBOOTVAR` and `CONFIG_FS_UBOOTVARFS` are the only two I really wanted from the upgrade. Maybe some changes came along with resaving the config file after the update? 

In any case, I'm thinking that the PR should be redone with the tagged Barebox release now that there's a tag. If I were to update it, I'd separate the commits so that the UBOOTVAR option gets enabled separately. 

You said that there's another issue. Is that related to this update?

**Comment by sylane** [comment]
No important issues, I changed to use the imx6ull image as it is the chip on the grisp2, tried to use the tag but you can't have a git sub-module from a tag, and tried to use the new CONFIG_EXTERNAL_DTS_FRAGMENTS instead of patching barebox but then there is name conflict so I left that for another time.
I pushed the changes to master, sorry to no use your PR as-is, I added you as co-author though.
I'll close this PR.

**Pull request closed without merging**
