### PR TITLE
fdt: Add pin initialization for missing connectors

### PR DESCRIPTION
**Pull request by c-mauderer**
This adds pin initialization for all connectors that were still missing from the FDT.

How do we want to make the pins accessible for the software in the gpio PMOD? We could for example add

```
grisp,gpios = <...>
```

to the new pmod_gpio section so that the software can parse that and access the pins.

### CODE REVIEW

**Comment by eproxus** [comment]
I feel I’m not competent enough with FDTs to judge the changes as they deserve. 

I think searching for FDT properties is the right way to go. If we stick to generic names, perhaps we could implement a runtime search instead of relying on overlay FDTs?

That is, kind of like the embedded Linux way but with GRiSP runtime code by us instead of hard coded overlays.

**Comment by c-mauderer** [comment]
It's basically no problem to add multiple "disabled" nodes that cover multiple cases. You can find these in your software using libfdt and for example pass the pinctrl-0 to the imx iomux driver so that it initializes that pin group. My problem basically is that I don't know what you need.

Like mentioned earlier, I think for the GPIO PMODs, a
```
grisp,gpios = <&gpio5 2 GPIO_ACTIVE_HIGH>,
    <&gpio3 1 GPIO_ACTIVE_HIGH>;
```
could be useful.

Note: On Linux if you have a GPIO, you normally use it for some special purpose like driving a LED, enabling some chip or starting a rocket (if you have a custom made foam rocket launchers). So you find GPIO attributes for these purposes. I haven't yet found one that would be a good match for some general purpose GPIO that should be controlled by the user space. That's why I suggested some custom `grisp,gpios`. We are writing something custom. So if you prefer, we could put any other label to that too. Basically: Check what would be the simplest method for your software to access these and then let's just use it. You can have a look at the LED initialization in libgrisp:

```
static void
grisp2_init_led_by_fdt(
	struct imx_gpio_pin *led,
	const void* fdt,
	const char *fdt_path
)
{
	rtems_status_code sc;
	int node;
	node = fdt_path_offset(fdt, fdt_path);
	sc = imx_gpio_init_from_fdt_property(led,
	    node, "gpios", IMX_GPIO_MODE_OUTPUT, 0);
	assert(sc == RTEMS_SUCCESSFUL);
	imx_gpio_set_output(led, 0);
}
```

The last parameter in the `imx_gpio_init_from_fdt_property` is the index of the GPIO in a list like in my example with the `grisp,gpios`.

**Comment by eproxus** [comment]
> It's basically no problem to add multiple "disabled" nodes that cover multiple cases. You can find these in your software using libfdt and for example pass the pinctrl-0 to the imx iomux driver so that it initializes that pin group. My problem basically is that I don't know what you need.

Hmm, let's try to gather some high-level requirements. What I would wish for as a end user is to have a GRiSP API where I could specify _any_ pin and control it over GPIO. That would ideally work for all pins on all slots, even e.g. the SPI slot (in case I wanted to repurpose it for extra GPIO).

I realize it might not be possible to go all the way towards such a dynamic system, but at least we need to be able to address all GPIO pins uniquely.

> Like mentioned earlier, I think for the GPIO PMODs, a
> 
> ```
> grisp,gpios = <&gpio5 2 GPIO_ACTIVE_HIGH>,
>     <&gpio3 1 GPIO_ACTIVE_HIGH>;
> ```
> 
> could be useful.

Is this a replacement for the already suggested `pmod-gpio` and `pins-gpio` groups? Or in addition?

> Note: On Linux if you have a GPIO, you normally use it for some special purpose like driving a LED, enabling some chip or starting a rocket (if you have a custom made foam rocket launchers). So you find GPIO attributes for these purposes. I haven't yet found one that would be a good match for some general purpose GPIO that should be controlled by the user space. That's why I suggested some custom `grisp,gpios`. We are writing something custom. So if you prefer, we could put any other label to that too.

I'm fine with any generic label for now, we can always change it later.

> Basically: Check what would be the simplest method for your software to access these and then let's just use it. You can have a look at the LED initialization in libgrisp:
> 
> ```
> static void
> grisp2_init_led_by_fdt(
> 	struct imx_gpio_pin *led,
> 	const void* fdt,
> 	const char *fdt_path
> )
> {
> 	rtems_status_code sc;
> 	int node;
> 	node = fdt_path_offset(fdt, fdt_path);
> 	sc = imx_gpio_init_from_fdt_property(led,
> 	    node, "gpios", IMX_GPIO_MODE_OUTPUT, 0);
> 	assert(sc == RTEMS_SUCCESSFUL);
> 	imx_gpio_set_output(led, 0);
> }
> ```
> 
> The last parameter in the `imx_gpio_init_from_fdt_property` is the index of the GPIO in a list like in my example with the `grisp,gpios`.

**Comment by c-mauderer** [comment]
> > It's basically no problem to add multiple "disabled" nodes that cover multiple cases. You can find these in your software using libfdt and for example pass the pinctrl-0 to the imx iomux driver so that it initializes that pin group. My problem basically is that I don't know what you need.
> 
> Hmm, let's try to gather some high-level requirements. What I would wish for as a end user is to have a GRiSP API where I could specify _any_ pin and control it over GPIO. That would ideally work for all pins on all slots, even e.g. the SPI slot (in case I wanted to repurpose it for extra GPIO).
> 
> I realize it might not be possible to go all the way towards such a dynamic system, but at least we need to be able to address all GPIO pins uniquely.
> 
> > Like mentioned earlier, I think for the GPIO PMODs, a
> > ```
> > grisp,gpios = <&gpio5 2 GPIO_ACTIVE_HIGH>,
> >     <&gpio3 1 GPIO_ACTIVE_HIGH>;
> > ```
> > could be useful.
> 
> Is this a replacement for the already suggested `pmod-gpio` and `pins-gpio` groups? Or in addition?
> 

That would be an addition. Basically the `pmod_gpio` node would look like follows (not with the correct GPIOs yet):

```
	pmod_gpio: pmod-gpio {
		pinctrl-names = "default";
		pinctrl-0 = <&pinctrl_gpio_pmod>;
		grisp,gpios = <&gpio5 2 GPIO_ACTIVE_HIGH>,
				<&gpio3 1 GPIO_ACTIVE_HIGH>,
				[...]
				<&gpio3 1 GPIO_ACTIVE_HIGH>;
		status = "okay";
	};
```

With that you could use libfdt to search for the `pmod_gpio` name (either by path or by alias) and then access the GPIOs with the `imx_gpio_init_from_fdt_property` and related functions.

If you want, we can make that for all PMOD connectors. The FDT is more or less a flexible data base for that kind of stuff. Your colleagues asked for the right `/dev/ttyS*` for the PMOD serial. If you want we can add a node

```
pmod_serial: pmod-serial {
	grisp,device = "/dev/ttyS3";
	grisp,gpios = <...>;
	pinctrl-names = "default", "gpio";
	pinctrl-0 = <&pinctrl_serial_pmod_default>;
	pinctrl-1 = <&pinctrl_serial_pmod_gpio>;
};
```

With that you could write software that uses this FDT "data base" and if we have a variant for the GRiSP2 that (for example) has the pmod-serial on a different port, we just change the FDT without a change in your software. That's the idea of the FDT. It's only not really useful if I try to write a FDT that might cover these cases. That is only useful if you want to use it in your software. It would only add dead code that might could even be irritating if I add stuff that you don't use.

> > Note: On Linux if you have a GPIO, you normally use it for some special purpose like driving a LED, enabling some chip or starting a rocket (if you have a custom made foam rocket launchers). So you find GPIO attributes for these purposes. I haven't yet found one that would be a good match for some general purpose GPIO that should be controlled by the user space. That's why I suggested some custom `grisp,gpios`. We are writing something custom. So if you prefer, we could put any other label to that too.
> 
> I'm fine with any generic label for now, we can always change it later.

**Comment by eproxus** [comment]
That sounds like a good idea. If you add the missing pins and serial entries, I can try to read them out using the FDT search functions.

**Comment by eproxus** [comment]
@c-mauderer If you rebase on master I've replaced `mkimage` from u-boot-tools with `mkimage.py` from RTEMS instead, that way the macOS builds works.

**Comment by c-mauderer** [comment]
@eproxus: I updated the FDT like discussed. There is now a node like `"/pmod_i2c"` and similar for each PMOD connector. Note that I moved some of the pinctrl-0 fields to these nodes because I think they make more sense there. Note that I didn't test whether all driver work without problems with that change. So please just tell me if something makes problems.

**Comment by eproxus** [comment]
@c-mauderer We've tried out the and it seems to work fine with our existing code. I'm trying to make an API to talk to the pins (which works initially).

One thing we could do on GRiSP one was to re-configure a pin to be input/output. Is this possible on GRiSP 2? I only see an API for initializing the pin with a certain direction, but no API for changing it. How should one go about that?

I found the undocumented functions `imx_gpio_direction_input(pin)` and `imx_gpio_direction_output(pin)`. Is it safe to call those? Is there a way to get the current direction of a pin?

**Comment by c-mauderer** [comment]
> @c-mauderer We've tried out the and it seems to work fine with our existing code. I'm trying to make an API to talk to the pins (which works initially).

Thanks for testing it.

> 
> One thing we could do on GRiSP one was to re-configure a pin to be input/output. Is this possible on GRiSP 2? I only see an API for initializing the pin with a certain direction, but no API for changing it. How should one go about that?

Hm. There is not really an API for that at the moment. I think the best way is most likely to change the `mode` in the structure and just call `imx_gpio_init()` again for that pin. You can use that even if you initialized the pin with `imx_gpio_init_from_fdt_property()` earlier. So (in pseudo code) that would be:

```
struct imx_gpio_pin my_pin;

/* some when during initialization */
imx_gpio_init_from_fdt_property(&my_pin, ..., IMX_GPIO_MODE_INPUT, ...);

/* changing the mode */
my_pin.mode = IMX_GPIO_MODE_OUTPUT;
imx_gpio_init(&my_pin);
```

With the current implementation of the driver, that is a save method to change the direction and it's not really much overhead compared to the (static) functions you mention below.

> 
> I found the undocumented functions `imx_gpio_direction_input(pin)` and `imx_gpio_direction_output(pin)`. Is it safe to call those? Is there a way to get the current direction of a pin?

These are static functions and they wouldn't change the "mode" of the imx_gpio_pin structure. So 1. you can't call them and 2. they wouldn't be save.

**Comment by eproxus** [comment]
@c-mauderer Thanks, I'll try using `imx_gpio_init(&pin)`. Is there a way to get the current direction of a pin?

**Comment by c-mauderer** [comment]
> @c-mauderer Thanks, I'll try using `imx_gpio_init(&pin)`. Is there a way to get the current direction of a pin?

Sorry, I missed that question. You can query the "mode" in the structure. As long as no one meddles with the low level registers, that will have the correct value (after you called `imx_gpio_init()`).

**Comment by eproxus** [comment]
@c-mauderer Perhaps a beginner C question, but is that "thread" safe? Or rather, multi-reference safe? I.e. can I call `imx_gpio_init_from_fdt_property()` and/or `imx_gpio_init` multiple times for the same pin and change the direction later and query it from all the structs?

**Comment by c-mauderer** [comment]
The method I suggested for changing / querying the direction is not thread save. I assumed that you have only one task that handles one pin. Sorry that I didn't explicitly mentioned that.

The driver does not check whether you initialize multiple structures for the same physical pin. So if you initialize and use one pin as an output from one thread and use and initialize the same pin as an input from another thread, the behavior will be undefined. To be honest: I can't really think of a use case for that. The pin is only there one time and I think you would get a lot of problems if two threads try to use it at the same time without synchronizing somehow who owns the pin at that moment. Do you have a use case where that would be necessary?

**Comment by peerst** [comment]
I have a question regarding `GPIO_ACTIVE_HIGH` what does that actually mean?  Does this mean its by default configured as a output or is that a input?  Which values exist for these?

**Comment by c-mauderer** [comment]
> I have a question regarding `GPIO_ACTIVE_HIGH` what does that actually mean? Does this mean its by default configured as a output or is that a input? Which values exist for these?

For Linux it means that a logic 1 is 3.3V and a logic 0 is 0V. GPIO_ACTIVE_LOW would mean a logic 1 is 0V and a logic 0 is 3.3V.

The driver for the i.MX on RTEMS just ignores that flag at the moment. So it's not relevant whether it is GPIO_ACTIVE_HIGH or some other value.

**Review by eproxus — APPROVED** [review]

**Comment by peerst** [comment]
Where and how is the port direction (input/output) and potential other features pulp/pulldown open-collector specified?

Which features exist in iMX6 and are all available in the driver?

**Comment by c-mauderer** [comment]
> Where and how is the port direction (input/output) and potential other features pulp/pulldown open-collector specified?
> 
> Which features exist in iMX6 and are all available in the driver?

You can set the port direction with the `mode` in the `imx_gpio_init_from_fdt_property`: https://github.com/grisp/rtems/blob/0fe6bd64cf9943e1fe9afa14aa4b3185cbea0735/bsps/arm/imx/include/bsp/imx-gpio.h#L79

Possible modes are:
```
  IMX_GPIO_MODE_OUTPUT,
  IMX_GPIO_MODE_INPUT,
  IMX_GPIO_MODE_INTERRUPT_LOW,
  IMX_GPIO_MODE_INTERRUPT_HIGH,
  IMX_GPIO_MODE_INTERRUPT_RISING,
  IMX_GPIO_MODE_INTERRUPT_FALLING,
  IMX_GPIO_MODE_INTERRUPT_ANY_EDGE,
```

Pull Up/Down and similar settings belong to the iomux peripheral. Therefore they are not in the imx_gpio driver but in a separate one. The iomux-driver gets the information how to initialize a pin from the fdt. You maybe have seen the odd magic numbers in the fdt iomuxc block:

```
	pinctrl_usdhc1: usdhc1grp {
		fsl,pins = <
			MX6UL_PAD_SD1_CMD__USDHC1_CMD		0x17059
			[...]
```
In that example, the 0x17059 is the value that is written into the `IOMUX_SW_PAD_CTL_PAD_*` register. The registers are all similar with very few exceptions. For the SD1_CMD register, the register looks like follows:

grafik

grafik

**Comment by eproxus** [comment]
That went a bit over my head for now. If I open a pin in output mode, will it be high or low by default?

**Comment by c-mauderer** [comment]
> That went a bit over my head for now. If I open a pin in output mode, will it be high or low by default?

At the moment: Undefined.

The imx_gpio driver sets the direction during the initialization but not the value. So it's whatever value has been in the register before you initialized the pin. The reset value of the GPIO_DR is 0 so in most cases it is low. But if some software used it earlier, it can be anything else too.

**Comment by eproxus** [comment]
Isn't that problematic, if the initial value will be "random"? Can you set the value before initializing the pin somehow?

**Comment by c-mauderer** [comment]
The whole state of the pin is random before you do anything with it. Of course we can for example set the pins to low or some user defined value during init. But it's not sure what mode the pin had before that. It could have been used by some other software part as an input or an output. It could have been used by the bootloader or it could still have it's reset value.

For all pins that haven't been touched before by other software, the initial state will be the reset state of the registers. That is: Input, low.

**Review by peerst — APPROVED** [review]

**Pull request merged**
