### PR TITLE
Fix USB caching problems. Update SPI driver. Fix Ethernet.

### PR DESCRIPTION
**Pull request by c-mauderer**
- The updates in RTEMS and libbsd fix the caching problem for the USB rtwn driver. With that a RTL8188 based (and similar) WLAN dongle will work.
- The SPI driver in RTEMS has been updated to use GPIOs for CS. The i.MX6 SPI module is not really designed to have chip selects controlled by a general driver framework like used in RTEMS, Linux or FreeBSD (although it looks like it could be great for a very specialized driver). Note that this **needs a FDT update** too!
- Some issues with Ethernet have been fixed.

### CODE REVIEW

**Comment by c-mauderer** [comment]
Sorry, missed a bug.

**Comment by c-mauderer** [comment]
I added a forced update to the current master and will merge it as soon as the checks have completed.

**Comment by c-mauderer** [comment]
This now also adds another SPI fix to RTEMS.

**Comment by c-mauderer** [comment]
Updated this branch again like discussed in issue #12

**Comment by eproxus** [comment]
@c-mauderer Thanks, I'll test and merge after the checks have passed 👍

**Pull request merged**
